### PR TITLE
Correct type definitions according to source repo

### PR DESCRIPTION
**Pull request by blakeembrey**

### CODE REVIEW

**Comment by blakeembrey** [comment]
@OlsonDev Fixed up the type definition as discussed in #1. It **can not** have a `default` because there's no `default` property in the source repo. Sorry I yelled in the issue, it's just I bang my head explaining this at least once a day and for some reason people like to work around it - which will only work on their mix up of a system (e.g. using babel + TS or SystemJS + TS which is doing automatic import renaming for them, which is _extremely_ fragile). In TypeScript, there's a directive you can enable for the SystemJS behaviour - something like `allowSyntheticDefault`.

**Comment by OlsonDev** [comment]
I understand your frustration -- sorry for being thick. I discarded all local changes and manually applied your changes, `npm install` `npm prune` `npm run watch` and got this:

```
> @ watch C:\Storage\Projects\typed-keyboardjs
> onchange "**/*.ts" -i -e "out/**" -- npm -s run build+test

source-test is not specified
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Also tried `npm run build` then `npm run test` and got:

```
> @ test C:\Storage\Projects\typed-keyboardjs
> browserify test/test.ts typings/main.d.ts out/main.d.ts -p [ tsify --noImplicitAny ] | tape-run --browser phantomjs

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

What am I missing?

**Comment by OlsonDev** [comment]
Also tried both `npm install -g phantomjs` and `npm install -g phantomjs-prebuilt`

**Comment by OlsonDev** [comment]
What the ... so, I had to `npm uninstall -g phantomjs`, `npm uninstall -g phantomjs-prebuilt`, download phantomjs from their site, unzip it & add it to my `PATH`, restart `cmd`, then `npm run test` worked.

Figured that out from https://github.com/nathanboktae/mocha-phantomjs/issues/61

I'm assuming you didn't have to do any of that crap... you're on OS X, right?

**Comment by blakeembrey** [comment]
@OlsonDev Yes, on OS X. Are your global NPM modules in your `PATH`? That should have worked for you.

**Comment by OlsonDev** [comment]
Definitely. For example:

```
C:\>where tsc
C:\Users\Olson\AppData\Roaming\npm\tsc
C:\Users\Olson\AppData\Roaming\npm\tsc.cmd
```

**Comment by blakeembrey** [comment]
Odd, not sure then. I'm pretty sure I just installed `phantomjs` with NPM.

**Comment by OlsonDev** [comment]
Yeah, I don't get it either. If you look at that issue, it's all Windows users who installed `phantomjs` with NPM... **shrugs** Oh well, it works now.

**Pull request merged**
